# ACL format:
# ACL ACTION PROTO SRC_IP SRC_PORT DST_IP DST_PORT
# ACTION = ALLOW or DENY
# ANY can be used as wildcard

ACL DENY TCP ANY ANY 10.0.0.10 22
ACL DENY UDP ANY ANY 10.0.0.20 53
ACL ALLOW ANY ANY ANY ANY ANY

# NAT format:
# NAT PRIVATE_CIDR PUBLIC_IP

NAT 10.0.0.0/24 203.0.113.10

# ROUTE format:
# ROUTE DEST_CIDR OUT_INTERFACE

ROUTE 10.0.0.0/24 eth1
ROUTE 8.8.8.0/24 eth0
ROUTE 0.0.0.0/0 eth0